env:
  browser: true
  es2020: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  no-debugger:
    - error
  no-console:
    - error
  react/jsx-curly-brace-presence:
    - warn
  no-use-before-define:
    - error
  react/jsx-key:
    - error
  no-loop-func:
    - error
  no-shadow:
    - error
  eqeqeq:
    - error
